### ISSUE TITLE
深色模式下标题字体为黑色

### ISSUE THREAD

**Issue by AirboZH** [AirboZH/halo-theme-chirpy#13]
深色模式下标题字体没有变化

**Comment by AirboZH** [comment]
![19633bbed0d6c156313c5fa413a779a](https://github.com/AirboZH/halo-theme-chirpy/assets/50261327/6c1283c7-79b7-45e0-b11b-36480be69be5)

黄色框的color覆盖了绿色部分的color导致文章title颜色是黑色的，但是这个

```css
.card-title {
    margin-bottom: var(--bs-card-title-spacer-y);
    color: var(--bs-card-title-color)
}
```

中的color还是未定义的

```css
.card {
    --bs-card-title-color: ;
}
```

scss中.card-title 类的颜色属性似乎并没有直接设置

scss是fork上游项目直接编译来的
