### ISSUE TITLE
图片、视频、嵌入网页啥的希望可以设置成圆角的。

### ISSUE THREAD

**Issue by shanyan-wcx** [AirboZH/halo-theme-chirpy#130]
个人觉得圆角的看起来风格比较统一。当然也可能有人不喜欢，所以希望有个开关选项就好了。

**Comment by AirboZH** [comment]
感谢你的建议，我试了一下，计划开发5px的圆角在图片上。

你可以在 https://www.airbozh.cn/archives/plugin-uposs 看到预览效果

如果对 5px 不满意的话，可以在 console - 设置 - 代码注入 - 内容页head标签中 插入以下css
```css
<style>
  img{
    border-radius: 5px;
  }
</style>
```
