### ISSUE TITLE
[改进] 表格显示样式问题

### ISSUE THREAD

**Issue by Rlxzmdd** [AirboZH/halo-theme-chirpy#148]
由markdown生成的表格第一行无局中效果。我看了下html代码，align为center。不明白咋搞了。
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/509cc9c8-0bbb-4b00-8533-ddca54626486)
同样的文章在官方主题下是这样的：
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/22d7361e-d692-4a79-aa8d-9399c604a1a3)

网站链接：https://have.somuch.work/archives/24.2.20-i2c-uart-spi-xie-yi-qu-bie

**Comment by Rlxzmdd** [comment]
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/d4647dc7-dece-40ea-a797-96d9db07d514)
查了下是这个样式引起的问题，注释掉就可以了
 
通过css代码注入改善了显示效果。
![image](https://github.com/AirboZH/halo-theme-chirpy/assets/13695917/8ae48158-0431-4bdb-8e52-33f5f07bb1d0)
下面是所使用到的样式：
```css
html[data-mode=light]  {
    --tb-bg: #f6f8fa;
    --tb-le: #d0d7de;
}

table tr {
    border-top: 1px solid var(--tb-le);
}
table tr:nth-child(2n) {
    background-color: var(--tb-bg);
}
table th, table td{
    padding: 6px 13px;
    border: 1px solid var(--tb-le);
}
@media (prefers-color-scheme: dark) {
  html{
    --tb-bg: #232323;
    --tb-le: #3a3a3a;
  }
 }
```
